services:
  db:
    image: mysql:8.0
    container_name: db_${PROJECT_DIR}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_${PROJECT_DIR}
    depends_on: [db]
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db

  maildev:
    image: maildev/maildev
    container_name: maildev_${PROJECT_DIR}
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "${MAILDEV_PORT}:80"
      - "25:25"                # SMTP

  www:
    platform: linux/amd64     # change en linux/arm64 si Mac M1/Raspberry
    build:
      context: .                # racine du dépôt
      dockerfile: php/Dockerfile
    container_name: ${PROJECT_DIR}
    ports:
      - "${WWW_PORT}:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./${PROJECT_DIR}/app:/var/www/app
    restart: always

volumes:
  mysql_data:
